### ISSUE TITLE
message.yml add please

### ISSUE THREAD

**Issue by LeePC** [DokanBoy/amongcraft#1]
Please add message.yml file

**Comment by DokanBoy** [comment]
Hi @LeePC 
At the moment, only the API for the mini-game is ready, in the near future I plan to add functionality and transfer the plugin to private use. If you want to access the plugin, you have to pay.
The language file will be added later.

**Comment by LeePC** [comment]
I'll pay 8 dollars, so can you make it for me?
But my YouTube revenue will be withdrawn on the 21st, so I will give it to you then.

**Comment by DokanBoy** [comment]
I will think about it, but 8 dollars is not enough. I would like to have at least 15 USD.
By what date do you need this plugin?
